name: Deploy to Shared Hosting ADS Site

on:
  push:
    branches:
      - main  # Change 'main' to your branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: 198.54.126.103
        username: adshrbgh
        port: 21098
        key: ${{ secrets.PRIVATE_SSH_KEY_ADS }}
        script: |
          cd /home/adshrbgh/public_html
          git pull origin main
       
